# These are supported funding model platforms

github: [ericrallen]
ko_fi: ericrallen
buy_me_a_coffee: interwebalchemy
custom:
  [
    "https://childsplay.salsalabs.org/Donate/index.html",
    "https://www.dotsrpg.org/donate",
    "https://supporters.eff.org/donate/",
    "https://ablegamers.org/invest-in-ablegamers/",
  ]
